### ISSUE TITLE
UAT fix: Dataset preview text

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#124]
Currently for the data dictionary, the text says. "You're previewing the first 50 rows of the file."

Change file to data dictionary.

(since this is not a downloadable files)

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is fixed
https://sandbox.data.ca.gov/preview?name=covid-19-wastewater-surveillance-data-california&id=16bb2698-c243-4b66-a6e8-4861ee66f8bf

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks! Please add to https://lab.data.ca.gov/ and let me know when it's ready for review.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review completed. The fix is not displaying in the lab to match this example:
![image](https://user-images.githubusercontent.com/99768807/188199217-6b7b8f2e-a99f-4e8f-a1a9-358a9ed23ffd.png)
[Figma Link](https://www.figma.com/file/vOHFU1P0uQ7JKuCY1bOzZt/Proof-of-concept-prototype?node-id=1517%3A51119)

Please fix and let me know when it's ready for review, thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
Here it is
https://sandbox.data.ca.gov/dataset/covid-19-wastewater-surveillance-data-california/16bb2698-c243-4b66-a6e8-4861ee66f8bf

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Great, thanks! Please add to https://lab.data.ca.gov/ and let me know when it's ready for review.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe FYI - @hamiltonryan can review the changes in https://lab.data.ca.gov/ while I'm OOO. 

Please tag Ryan so he can let you know if there's a concern, or if this issue is complete and closed. 
Ryan, please also go to the [ODP Project Board](https://github.com/orgs/CA-Data/projects/1 ) and move this issue's card to "Done - In Production". Thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang  @hamiltonryan 
This is now on lab
https://lab.data.ca.gov/dataset/covid-19-wastewater-surveillance-data-california/16bb2698-c243-4b66-a6e8-4861ee66f8bf
