### ISSUE TITLE
UAT Fix: Contact us tasks

### ISSUE THREAD

**Issue by extinah** [CA-Data/Open-Data-Portal#125]
Things to work on:

**Drop-down**: Remove Upload and Search from the topic dropdown.

**Error messages** aren't behaving as expected. It only displays an error once you interact with it
![image](https://user-images.githubusercontent.com/33840424/180332797-5eef4571-093c-48e4-a7d5-6fd46298b92f.png)

Odd message: "This form is not secure. Auto-fill has been turned off." Look into different ways to send emails (SendGrid). Have the email sent on the serverside.

![image](https://user-images.githubusercontent.com/33840424/180332951-d5c22b8a-edc5-4e70-becb-d9ec18820dbe.png)

**Comment by sharon-rabang** [comment]
@timothyshambra Please work on this one, since you're familiar with it. Thanks!

**Comment by sharon-rabang** [comment]
Reassigning to @Greg-Watanabe. Please reach out to Tim if you have any questions.

**Comment by sharon-rabang** [comment]
Update at stand-up: @Greg-Watanabe and @timothyshambra are working on looking for an account to use for a SMTP relay, instead of using a free Email JS account. 

Note from @sam-hayashi in chat: We just added a reCAPTCHA filtering system on the production CKAN portal. Prior to that we were probably right at 200 emails a month that were delivered through the Contact Us page. Would is be possible to add a reCAPTCHA filter on the NextGen email system as well?

**Comment by Greg-Watanabe** [comment]
@sharon-rabang 
This is partly done. Validation is fixed, and it's using emailjs and a gmail account to send the submissions.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Thanks for the status update! Will stay tuned for the next one.

**Comment by sharon-rabang** [comment]
Status update: Greg waiting for GovOps to open an IP between EmailJS and SendGrid.

**Comment by sharon-rabang** [comment]
@Greg-Watanabe @timothyshambra FYI - @hamiltonryan can review the changes in https://lab.data.ca.gov/ while I'm OOO. 

Please tag Ryan so he can let you know if there's a concern, or if this issue is complete and closed. 
Ryan, please also go to the [ODP Project Board](https://github.com/orgs/CA-Data/projects/1 ) and move this issue's card to "Done - In Production". Thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang  @hamiltonryan 
What's the email address where these form submission should be sent?

**Comment by sharon-rabang** [comment]
@Greg-Watanabe @hamiltonryan, will ask Sam:
@sam-hayashi Can you help provide us with the official email address for these form submissions?

**Comment by sam-hayashi** [comment]
Hi @Greg-Watanabe @hamiltonryan @sharon-rabang  - please use opendata@state.ca.gov. Thanks!

**Comment by Greg-Watanabe** [comment]
@sharon-rabang  @hamiltonryan 
This is compete
https://lab.data.ca.gov/contact-us

**Comment by sharon-rabang** [comment]
@Greg-Watanabe Review and test completed. My test form submission was received by opendata@state.ca.gov, and this  confirmation page appeared:
![image](https://user-images.githubusercontent.com/99768807/189761215-4b5e1e9f-8282-4e12-9461-ec37e1899076.png)

Closing this issue, thanks!
